enable_compute                   = true
enable_loadbalancer              = true
enable_database                  = true
project_name                     = "etithe"
environment                      = "dev"
aws_region                       = "us-east-1"
aws_profile                      = "etithe"
app_port                         = 30080
database_instance_class          = "db.t4g.micro"
database_allocated_storage       = 20
database_backup_retention_period = 1
database_name                    = "etithe"
database_master_username         = "etithe_admin"
database_allowed_cidr_blocks     = ["10.20.11.0/24", "10.20.12.0/24"]
vpc_cidr                         = "10.20.0.0/16"
public_subnet_cidrs              = ["10.20.1.0/24", "10.20.2.0/24"]
private_subnet_cidrs             = ["10.20.11.0/24", "10.20.12.0/24"]
availability_zones               = ["us-east-1a", "us-east-1b"]
