apiVersion: v1
kind: Service
metadata:
  name: etithe-app
  namespace: etithe
  labels:
    app: etithe-app
spec:
  selector:
    app: etithe-app
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30080
  type: NodePort
