# docker-compose.yml
services:
  etithe-app:
    build:
      context: ../etithe-app
      dockerfile: Dockerfile
    environment:
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - AUTH_DEMO_EMAIL=admin@church.org
      - AUTH_DEMO_PASSWORD=changeme
    ports:
      - "3000:3000"